<?php

namespace ContainerUyT3G8N;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDoctrineMigrations_SchemaFilterListenerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'doctrine_migrations.schema_filter_listener' shared service.
     *
     * @return \Doctrine\Bundle\MigrationsBundle\EventListener\SchemaFilterListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-migrations-bundle/src/EventListener/SchemaFilterListener.php';

        return $container->privates['doctrine_migrations.schema_filter_listener'] = new \Doctrine\Bundle\MigrationsBundle\EventListener\SchemaFilterListener('doctrine_migration_versions');
    }
}
