<?php

namespace ContainerUyT3G8N;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getImportsServiceService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'App\Services\ImportsService' shared autowired service.
     *
     * @return \App\Services\ImportsService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Services/ImportsService.php';

        return $container->services['App\\Services\\ImportsService'] = new \App\Services\ImportsService(\dirname(__DIR__, 4));
    }
}
