<?php

namespace ContainerEIytqxR;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getErrorsService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'App\Messages\Errors' shared autowired service.
     *
     * @return \App\Messages\Errors
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Messages/Errors.php';

        return $container->services['App\\Messages\\Errors'] = new \App\Messages\Errors();
    }
}
