<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEIytqxR\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEIytqxR/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerEIytqxR.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerEIytqxR\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerEIytqxR\App_KernelTestDebugContainer([
    'container.build_hash' => 'EIytqxR',
    'container.build_id' => '2b11d8f6',
    'container.build_time' => 1740647268,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEIytqxR');
