<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUTXedbd\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUTXedbd/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUTXedbd.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUTXedbd\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUTXedbd\App_KernelDevDebugContainer([
    'container.build_hash' => 'UTXedbd',
    'container.build_id' => '8f86c06a',
    'container.build_time' => 1740622091,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUTXedbd');
