on: [pull_request]
name: Main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Configure Git to trust the repository directory
        run: git config --global --add safe.directory /app
      - uses: actions/checkout@v3

      - name: Debug repository content
        run: ls -la
        
      - name: Install Composer
        uses: php-actions/composer@v6
        with:
          php_version: 8.2

      # Fix permissions before composer operations
      # If not some composer operations that need to update autoloader files will fail
      - name: Fix directory permissions
        run: sudo chown -R $USER:$USER .

      - name: Install Dependencies
        run: composer install

      - name: Cache composer store
        uses: actions/cache@v3
        with:
          path: ~/vendor
          key: ${{ runner.OS }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.OS }}-composer-

      - name: Lint PHP
        run: find . -name "*.php" -type f -not -path "./vendor/*" -not -path "./var/*" -exec php -l {} \;

      - name: Lint Style
        run: vendor/bin/php-cs-fixer fix --diff --dry-run

      - name: Setup test db
        run: php bin/console doctrine:database:create --env=test

      - name: Run migrations
        run: php bin/console doctrine:migrations:migrate --env=test -n

      - name: Run tests
        run: vendor/bin/phpunit

      - name: Debug PHPUnit
        run: vendor/bin/phpunit --debug --verbose

